### ISSUE TITLE
DumpRegister has certain rows swapped

### ISSUE THREAD

**Issue by jclapis** [Microsoft/Quantum#148] opened 2019-03-07 00:04 UTC
Hi guys,

I'm sure this isn't the correct place to report this, but as far as I can tell the Microsoft.Quantum.Extensions namespace lives in the Primitives library and that isn't open sourced. I just don't know where else to put it or who to submit it to. Anyway, during my experiments I've run into two issues with DumpRegister - one of them is just a documentation thing, but I believe the other might be a bug.

### Documentation Issue
The documentation issue is simply that DumpRegister seems to expect the register in little-endian format, but doesn't explicitly say that anywhere. Once you run it and look at the output, you get a message like this:
```
# wave function for qubits with ids (least to most significant): 0;1;2
```
So it does tell you that it will assume the register is little-endian, but the [documentation for it](https://docs.microsoft.com/en-us/qsharp/api/prelude/microsoft.quantum.extensions.diagnostics.dumpregister) doesn't mention that anywhere. It's easy to fix once you know what the function expects, it's just confusing at first since most of the literature (including the Katas) treats registers as big-endian.

### Potential Bug
The bigger issue I'm seeing is that sometimes, the dumped states seem to be out of order. I ran into this while testing the [canon QFT implementation](https://github.com/Microsoft/QuantumLibraries/blob/master/Canon/src/QFT.qs) with a 4-qubit register:
```
operation QftSandbox() : Unit
{
	using(register = Qubit[4])
	{
		X(register[3]);

		mutable le = BigEndianToLittleEndian(BigEndian(register));
		Message("Start: ");
		DumpRegister((), le!);
			
		QFT(BigEndian(register));

		set le = BigEndianToLittleEndian(BigEndian(register));
		Message("After QFT: ");
		DumpRegister((), le!);

		ResetAll(register);
	}
}
```
This will run QFT on the state **|0001>** which should produce a nice Heyser spiral like this: 
![image](https://user-images.githubusercontent.com/627896/53922009-b0cfbe00-4040-11e9-8b45-b2e2fa9f1314.png)

However, this is the QFT output:
```
Start: 
# wave function for qubits with ids (least to most significant): 3;2;1;0
0:	0	0
1:	1	0
2:	0	0
3:	0	0
4:	0	0
5:	0	0
6:	0	0
7:	0	0
8:	0	0
9:	0	0
10:	0	0
11:	0	0
12:	0	0
13:	0	0
14:	0	0
15:	0	0
After QFT: 
# wave function for qubits with ids (least to most significant): 3;2;1;0
0:	0.25	0
1:	0.230969883127822	0.0956708580912724
2:	0.176776695296637	0.176776695296637
3:	0.0956708580912725	0.230969883127822
4:	0	0.25
5:	-0.0956708580912724	0.230969883127822
6:	-0.25	0
7:	-0.230969883127822	-0.0956708580912724
8:	-0.176776695296637	0.176776695296637
9:	-0.230969883127822	0.0956708580912725
10:	0	-0.25
11:	0.0956708580912724	-0.230969883127822
12:	-0.176776695296637	-0.176776695296637
13:	-0.0956708580912725	-0.230969883127822
14:	0.176776695296637	-0.176776695296637
15:	0.230969883127822	-0.0956708580912725
```
When graphed (I used [plotly](https://plot.ly/create/#/)), it looks like this:
![image](https://user-images.githubusercontent.com/627896/53922129-115efb00-4041-11e9-97f5-784cccd328cf.png)

This looks like a mess after the 6th element, but the problem is pretty simple: **some of the elements are in the wrong order**. For this specific example, the following pairs needed to be swapped (note, these are **zero-indexed**):
6 and 8
7 and 9
10 and 12
11 and 13

With those elements swapped, the result looks correct. This could be a bug with QFT as well, but it seems to be giving me the expected answers so far. This problem doesn't happen with a 3-qubit register, I've only seen it on registers with 4+ qubits.

**Comment by anpaz-msft** [comment] 2019-03-07 18:14
Thanks for the detailed report. As you can see we moved it to the /Quantum repository where we're tracking general bugs in the Quantum Development Kit.

I can confirm this is unrelated to `QFT`. The following code shows the same behavior:

```
open Microsoft.Quantum.Extensions.Diagnostics;

operation DumpTest() : Unit
{
	using(q = Qubit[4])
	{
		X(q[1]);
		X(q[2]);

		// These should all be equivalent
		DumpRegister((), [q[0],q[1],q[2],q[3]]);
		DumpRegister((), [q[3],q[1],q[2],q[0]]);
		DumpRegister((), [q[3],q[2],q[1],q[0]]);
		DumpRegister((), [q[0],q[2],q[1],q[3]]);
			
		ResetAll(q);
	}
}
```

The output of `DumpRegister` above should be the same case in all cases, but when we change the order of `q[2]` and `q[1]`, then we see that 6 & 8 changes places, which I also believe shouldn't be the case.

I'll take a closer look, but I believe the issue is somewhere on how we calculate the wavefunction of the subsystem generated by the given in the argument. I'll keep you posted.

**Comment by anpaz-msft** [comment] 2019-03-21 19:24
Just a quick note to let you know we have identified the problem and are hoping to get it fixed on our next release.  I'll close the bug once it gets released.

**Comment by jclapis** [comment] 2019-03-21 19:27
Excellent, thanks guys! Looking forward to it.

**Comment by anpaz-msft** [comment] 2019-03-28 15:49
This is now fixed with yesterday's release. Give it a try and let us know otherwise.
Thanks again.

**Closed by anpaz-msft** 2019-03-28 15:49 UTC
Labels: bug
