### ISSUE TITLE
State-Visualizer: 'QsMain' does not exist in the current context

### ISSUE THREAD

**Issue by isaac-gs** [microsoft/Quantum#316] opened 2020-02-18 04:28 UTC
**Describe the bug**
Operations in .qs files are not recognized in the project. If I place the quantum code in a project where the sdk is set to Microsoft.Quantum.Sdk/0.10.2001.2831 (in the csproj file) it works fine. All other projects under "samples" build fine, so I think it's related to the use of "Microsoft.NET.Sdk.Web". When it does fail, the following is what I get.

**Program.cs(21,32): error CS0103: The name 'QsMain' does not exist in the current context [*\Quantum\samples\runtime\state-visualizer\StateVisualizer.csproj]**

This very well could be something I've done wrong, as I've checked multiple versions of this code (back until one in January - Commit d516ef97) and the same thing happens.

**To Reproduce**
1. Follow setup instructions for Q# development (I did Visual Studio and VS Code). [Q# + C# Instructions](https://docs.microsoft.com/en-us/quantum/install-guide/csinstall?view=qsharp-preview#VSC)
2. Verify setup is correct as in the instructions with a few simple programs from the Quantum Katas or other samples.
3. Follow instructions [here](https://github.com/microsoft/Quantum/tree/master/samples/runtime/state-visualizer)

**Expected behavior**
Expect for the code to run and for me to be able to access the visualizer at localhost:5000.

**System information**
 - OS: Windows
 - Browser: Chrome (but didn't get that far)
 - Version: 0.10.2001.2831 (and older versions)

**Comment by marshallsa** [comment] 2020-02-21 01:49
Hi @isaac-gs, just wanted to confirm some more information about the bug:

1. Does it happen in a freshly cloned copy of the repository, with no changes to the files before running `npm install`, `npm run release`, and `dotnet run`?
2. What version of .NET Core are you using? You can see it with `dotnet --version`.
3. Could you save the output of `dotnet build --verbosity detailed` to a file and attach it here?

Thanks!

**Comment by isaac-gs** [comment] 2020-02-22 04:53
Yeah it still happens on a fresh clone with no changes.

.NET Core Version: 3.1.101

[verbose_build.txt](https://github.com/microsoft/Quantum/files/4238818/verbose_build.txt)

**Comment by cgranade** [comment] 2020-02-25 18:05
We just saw another example yesterday of problems arising from spaces in folder names, perhaps this is related to https://github.com/microsoft/qsharp-compiler/issues/333?

**Comment by cgranade** [comment] 2020-04-27 23:37
@isaac-gs: I just wanted to quickly confirm if moving the same to another folder helped resolve the issue. Thanks!

**Comment by deonlewisduke** [comment] 2020-05-09 03:57
I'd reproduce the big for you but the only thing I can play with is QUIRK cause it works on $50 phone. I'm working a file structure for using the quantum effect as I'm calling where the programs have the appeared ability to violate what we know as possible, or what we can process with our strange units. Maybe, one day the half a million hackers who sabatoged my life will be taken care of.

**Comment by isaac-gs** [comment] 2020-05-09 04:38
@cgranade yes, it works. Sorry for the late reply, I've been busy. Thank you both for the help.

**Comment by samarsha** [comment] 2020-06-18 20:03
I found the cause of microsoft/qsharp-compiler#333, and I think that this bug is actually separate from that, so I'm reopening this.

**Comment by samarsha** [comment] 2020-06-19 01:42
The bug should be fixed by microsoft/qsharp-runtime#268, but the package references here will need to be updated to use the new version of Microsoft.Quantum.Development.Kit.

**Comment by samarsha** [comment] 2020-08-14 23:54
StateVisualizer.csproj no longer uses the Microsoft.Quantum.Development.Kit package, so I think this bug is resolved now.

**Closed by samarsha** 2020-08-14 23:54 UTC
Labels: Area-Samples, bug
