### ISSUE TITLE
Unittest failures in build which don't seem related to code changes

### ISSUE THREAD

**Issue by RolfHuisman** [Microsoft/Quantum#66] opened 2018-06-27 14:02 UTC
If I look through https://travis-ci.org/Microsoft/Quantum/pull_requests i see a lot of failed builds, based on test failures that don't seem to be related to the change:

E.g.
https://travis-ci.org/Microsoft/Quantum/builds/396937185, log: https://api.travis-ci.org/v3/job/396937187/log.txt
 RepeatUntilSuccessCircuitsTest, Seed: 525109616
 MeasureWithScratchTest, Seed: 1049631137
 BitFlipSampleWt1CorrectionTest, Seed: 3681483977
 EstimateFrequencyTest, Seed: 2566129342
 KDTest, Seed: 1627590700
 KnillDistillationNoErrorTest, Seed: 4166661619
 BayesianPEManualTest, Seed: 3270398307
 Pi4YInjectionTest, Seed: 223591028   
 SingleQubitProcessTomographyMeasurementTest, Seed: 42796896
https://travis-ci.org/Microsoft/Quantum/builds/396906712, log: https://api.travis-ci.org/v3/job/396906714/log.txt
 SuperdenseCodingTest, Seed: 2280605845
 RepeatUntilSuccessStatePreparationTest, Seed: 4294571069
 RepeatUntilSuccessCircuitsTest, Seed: 587399533
 MeasureWithScratchTest, Seed: 2431261675
 BitFlipSampleWt1CorrectionTest, Seed: 3472194629
 EstimateFrequencyTest, Seed: 4232379153
 KDTest, Seed: 2963729218
 Pi4YInjectionAdjointTest, Seed: 1062934322
 KnillDistillationNoErrorTest, Seed: 1606786275
 BayesianPEManualTest, Seed: 1717820587
 Pi4YInjectionTest, Seed: 4254770888

Based on trying to reproduce the seeds, they don't give issues.
Other builds also seem to have this behavior; 
https://travis-ci.org/Microsoft/Quantum/builds/396394544, log: https://api.travis-ci.org/v3/job/396394546/log.txt
https://travis-ci.org/Microsoft/Quantum/builds/396372255, log: https://api.travis-ci.org/v3/job/396372257/log.txt
https://travis-ci.org/Microsoft/Quantum/builds/396045024, log: https://api.travis-ci.org/v3/job/396045026/log.txt

So I'm hypothesising its caused by either; an order of test or something that's not disposed.
Needs more diagnosing.

**Comment by RolfHuisman** [comment] 2018-06-27 14:21
Deltafication of the logs shows something strange; <img width="116" alt="leftpass rightfail" src="https://user-images.githubusercontent.com/39134931/41980091-3c693cf2-7a58-11e8-8558-29e030fe6a11.PNG">
Wouldn't expect the linux and mac server to differ that much.

**Comment by qubeat** [comment] 2018-06-27 15:06
May be related?: H2 simulation works with error after other tests (or if you simply run it few times) https://quantum.uservoice.com/forums/906946-samples-and-documentation

**Comment by anpaz-msft** [comment] 2018-06-27 18:04
I noticed this problem too, and I have trying to reproduce it with no success. As you point out is not the seed. Could be that we're not releasing resources. My intuition, though, is that this is a multi-threading problem, however you should be able to create multiple instances of a Simulator and run each one in parallel (which is what the tests would do), so I'm confused about what the actual problem is.
@qubeat, the H2 problem could be related, however the h2 simulation is random in nature, and we are not providing a seed, so it's not too surprising to see random failures in it.
If you guys find out anything, please let us know.

**Comment by qubeat** [comment] 2018-06-27 18:30
@anpaz-msft  The failures are too big and not quite random (most are around -0.4). They also seem never appear at first run of dotnet. Seems the more runs, the more errors. Below rather an illustrative example:
![h2sim_err3_graph](https://user-images.githubusercontent.com/15838899/41992473-0d67a99a-7a38-11e8-9252-508a8a29d4b6.png)

**Comment by anpaz-msft** [comment] 2018-06-27 19:12
The H2 simulation algorithm is probabilistic at different levels and it's not unexpected to see it failing; the reason for the jumps you see there is that the algorithm is finding not the ground state but a higher excitation level, which is an expected result. If you look carefully at the code, you'll notice that for each bond length we calculate the energy 3 times and select the minimum value, because, again the result may give you any excitation level and not just the ground state.

**Comment by qubeat** [comment] 2018-06-28 13:01
@anpaz-msft  I change code to repeat 5 times and it seems work better, at least no errors after couple runs in VS Code. However I am not sure about excited states, it may be some calculation artifact as well - there is a "pit" on graphs

**Comment by RolfHuisman** [comment] 2018-06-29 14:45
Starting to suspect the init or destroy method in Microsoft.Quantum.Simulator.Runtime.dll. Validating hypothesis.

**Comment by RolfHuisman** [comment] 2018-06-30 13:38
Had a linux machine run "while dotnet test Samples/UnitTesting; do :; done;" and "while dotnet test LibraryTests; do :; done;" for a number of hours on a 2 vcpu, ubuntu machine but can't seem to repro this.

**Comment by RolfHuisman** [comment] 2018-06-30 13:41
Hmm.. LibraryTest seems to lock up with
> Measured: [One;Zero;Zero;One]
> measured: [Zero;One;Zero;One]
> measured: [One;One;Zero;One]
> measured: [Zero;Zero;One;One]
> measured: [One;Zero;One;One]
> measured: [Zero;One;One;One]
> measured: [One;One;One;One]"

as the last output

**Comment by RolfHuisman** [comment] 2018-06-30 20:30
> Testing ExpIZArcTan2NC against Exp{_}. Attempt: 0
> Trying ...
> [xUnit.net 00:00:15.6653463]     RepeatUntilSuccessCircuitsTest [FAIL]
> Failed   RepeatUntilSuccessCircuitsTest
> Error Message:
>  Microsoft.Quantum.Simulation.Core.ExecutionFailException : Error:the probability to measure |+⟩ in the first ancilla must be 0.5
>         Expected:       0.5
>         Actual: 0.166666666666667
> Stack Trace:
>    at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.QSimAssertProb.<get_Body>b__6_0(ValueTuple`6 _args)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Microsoft.Quantum.Simulation.Core.ICallable<I,O>.Apply(I args)
>    at Microsoft.Quantum.Samples.UnitTesting.ExpIZArcTan2NC.<get_Body>b__54_0(Qubit __in) in /home/reddog/Quantum/Samples/UnitTesting/RepeatUntilSuccessCircuits.qs:line 88
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Microsoft.Quantum.Simulation.Core.ICallable.Apply(Object args)
>    at Microsoft.Quantum.Canon.ApplyToFirstQubit.<>c.<get_Body>b__7_0(ValueTuple`2 __in) in /home/reddog/Quantum/Microsoft.Quantum.Canon/Combinators/ApplyToFirst.qs:line 28
>    at Microsoft.Quantum.Simulation.Core.PartialApplication`3.<get_Body>b__20_0(P a)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Microsoft.Quantum.Simulation.Core.ICallable.Apply(Object args)
>    at Microsoft.Quantum.Extensions.Testing.AssertOperationsEqualReferenced.<get_Body>b__27_0(ValueTuple`3 __in)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Microsoft.Quantum.Simulation.Core.ICallable<I,O>.Apply(I args)
>    at Microsoft.Quantum.Samples.UnitTesting.RepeatUntilSuccessCircuitsTest.<get_Body>b__34_0(QVoid __in) in /home/reddog/Quantum/Samples/UnitTesting/RepeatUntilSuccessCircuitsTests.qs:line 42
>    at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
>    at Microsoft.Quantum.Simulation.XUnit.TestOperation.<get_TestOperationRunner>b__6_0(IOperationFactory sim) in C:\build-agent\_work\7\s\src\simulation\Testing\TestOperation.cs:line 40
>    at Microsoft.Quantum.Samples.UnitTesting.SimulatorTestTargets.QuantumSimulatorTarget(TestOperation operationDescription) in /home/reddog/Quantum/Samples/UnitTesting/QuantumSimulatorTestTargets.cs:line 59
> Standard Output Messages:
>  The seed used for this test is 763837676
>  Testing ExpIZArcTan2NC against Exp{_}. Attempt: 0
>  Trying ...
> 
> 
> 
> Total tests: 15. Passed: 12. Failed: 3. Skipped: 0.
> Test Run Failed.
> Test execution time: 17.2773 Seconds
> rolf@Blade:~/Quantum$
>

**Comment by RolfHuisman** [comment] 2018-06-30 20:33
export OMP_NUM_THREADS=1 makes the tests run correctly, export OMP_NUM_THREADS=2 makes it fail. So it implies there is a race condition i.c.w. OpenMP.

**Comment by RolfHuisman** [comment] 2018-06-30 20:51
Repro steps I used
Spin up on Azure a "Ubuntu Server 14.04 LTS" from Canonical (Standard B2s (2 vcpus, 4 GB memory))

> wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
> sudo dpkg -i packages-microsoft-prod.deb
> sudo apt-get install apt-transport-https
> sudo apt-get update
> sudo apt-get install dotnet-sdk-2.1
> sudo apt-get install git
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install g++-4.9
> git clone https://github.com/Microsoft/Quantum.git
> cd Quantum
> dotnet build
> dotnet test Samples/UnitTesting

Should get:

> Total tests: 15. Passed: 12. Failed: 3. Skipped: 0.
> Test Run Failed.

**Comment by anpaz-msft** [comment] 2018-07-02 06:04
A bug on OpenMP is right on the money of where we were betting the problem would be.
Because this appears to be solved on the latest version and you found a workaround for travis, I don't want to do any changes on our end (like statically linking OpenMP) to fix it.
I will accept the change to reduce the number of threads on travis to 1 so we don't see this failures anymore.

**Comment by anpaz-msft** [comment] 2018-07-02 18:53
Thanks @RolfHuisman, I've merged the changes.

**Closed by anpaz-msft** 2018-07-02 18:53 UTC
