### ISSUE TITLE
QDK Error

### ISSUE THREAD

**Issue by yezz123** [microsoft/Quantum#391] opened 2020-08-01 12:54 UTC
I've recently tried to install the QDK via the VSCode extension in my Windows 10 Desktop and VSCode wasn't able to find the Microsoft libraries even after I was able to execute the code by the dotnet run command on the terminal. The code was the sample project code described in the create new project part of the tutorial. I also didn't have .NET SDK so I installed it but it seems to be working fine. In computers I got problems all the code, all related to not finding the namespaces.

**Comment by cgranade** [comment] 2020-08-06 15:57
Thanks for the report, @yezz123. Would you be willing to share the exact code that you tried, and what error messages you got when you ran `dotnet run`? Thank you!

**Comment by mitratul** [comment] 2020-08-25 00:20
I think what @yezz123 reported is similar to this: https://stackoverflow.com/questions/53925337/q-intellisense-errors. the program still runs fine with dotnet run.
I got it the last week too. Following is the exact code sample, and version details:
Right now I am at the basics of Q#, so I can just keep typing by looking at sample code. However, when I start writing new code, having the VSCode intellisense working will be of great help. @cgranade Let me know if you need anything else.

.NET core version: 3.1.401
Microsoft Quantum Development Kit for Visual Studio Code version: v0.12.20072031

![image](https://user-images.githubusercontent.com/6820274/91108418-e7cad280-e62c-11ea-8bbb-a753a7f13f1b.png)
![image](https://user-images.githubusercontent.com/6820274/91108717-996a0380-e62d-11ea-942c-6efcbcc9e0a9.png)

Code: 
namespace QuantumRNG {
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Measurement;
    open Microsoft.Quantum.Math;
    open Microsoft.Quantum.Convert;    

    operation GenerateRandomBit() : Result {
        using (q = Qubit()) {
            H(q);
            return MResetZ(q);
        }
    }

    operation SampleRandomNumberInRange(max : Int) : Int {
        mutable output = 0;
        repeat {
            mutable bits = new Result[0];
            for (idxBit in 1..BitSizeI(max)) {
                set bits += [GenerateRandomBit()];
            }
            set output = ResultArrayAsInt(bits);
        } until (output <= max);
        return output;
    }

    @EntryPoint()
    operation SampleRandomNumber() : Int {
        let max = 50;
        Message($"Sampling a random number between 0 and {max}: ");
        return SampleRandomNumberInRange(max);
    }
}

**Comment by guenp** [comment] 2020-12-21 17:26
This problem looks similar to this issue: https://github.com/microsoft/Quantum/issues/362
I am curious if this is still an issue with the latest version; I am not able to reproduce this.

**Comment by cgranade** [comment] 2021-03-18 15:38
Closing for now since we can't reproduce, but please feel free to reopen if you have additional information. Thank you!

**Closed by cgranade** 2021-03-18 15:38 UTC
Labels: Status-NeedMoreInfo, bug
