### ISSUE TITLE
Some commands are shown as text

### ISSUE THREAD

**Issue by hishikitetsuya** [microsoft/Quantum#272] opened 2019-11-24 12:00 UTC
\ket, \braket, and \boldone are shown as plain text, rather than equations.

![screenshot](https://user-images.githubusercontent.com/6519947/69494308-5099e880-0efd-11ea-8f50-2e59bfa2d8ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa16f624-d069-8384-a57d-b2c5be9513b0
* Version Independent ID: 7ac6e461-00e4-bdcf-5705-26990398174a
* Content: [Microsoft.Quantum.Intrinsic - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic?view=qsharp-preview)
* Content Source: [api/qsharp/Microsoft.Quantum.Intrinsic.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/Microsoft.Quantum.Intrinsic.yml)
* Product: **quantum**
* GitHub Login: @anpaz-msft

**Comment by cgranade** [comment] 2019-11-24 13:32
Thanks for reporting this, @hishikitetsuya! It looks like this is a duplicate of issue #271, so I'll go on and close this as a duplicate so that we can track the work there. Please feel free to re-open if that is incorrect. Thanks again for the help!

**Closed by cgranade** 2019-11-24 13:32 UTC
