### ISSUE TITLE
Need to use "Open" statement for every Jupyter Cell?

### ISSUE THREAD

**Issue by christopherkang** [microsoft/Quantum#393] opened 2020-08-02 19:47 UTC
[Not a bug report]

Is it necessary to use an "open" statement for every cell in Jupyter? For example, is there a way to globally import "Microsoft.Quantum.Arithmetic", so that the open statement doesn't need to be run on each cell beforehand?

**Comment by cgranade** [comment] 2020-08-02 20:36
@christopherkang: This just changed in the previous release, so that you can now have a single open cell apply across an IQ# notebook! Check out https://github.com/microsoft/iqsharp/issues/121 for more details and discussion. Thanks for raising this!

**Comment by cgranade** [comment] 2020-08-02 20:37
I'm going to go on and close this as a duplicate of https://github.com/microsoft/iqsharp/issues/121, but please feel free to reopen if that's not the case, or if there's any other details that would be helpful. Thanks!

**Closed by cgranade** 2020-08-02 20:37 UTC

**Comment by rmshaffer** [comment] 2020-08-04 01:03
Tagging another related issue: https://github.com/microsoft/iqsharp/issues/15.

**Comment by christopherkang** [comment] 2020-08-05 23:33
Awesome! I'll make sure I'm updated and check it out. Thank you both!
