### ISSUE TITLE
Python interops with numpy arrays

### ISSUE THREAD

**Issue by ValentinS4t1qbit** [Microsoft/Quantum#149] opened 2019-03-08 01:40 UTC
Currently, the Python interops do not support numpy arrays as arguments. A lot of Python users and packages rely on numpy arrays since there are no built-in arrays available in Python, and it would be desirable for the python interops to be able to translate internally a numpy array as an array of float, int or booleans (e.g simply expose the data in Q# operations as a Double[], Int[], Bool[]).

Supporting 1D numpy arrays for these datatypes would already take us a long way, and could be generalized to multidimensional arrays later, if possible.

**Comment by cgranade** [comment] 2019-03-08 07:17
Thanks for the report, @ValentinS4t1qbit! We're currently tracking this at https://github.com/Microsoft/QuantumLibraries/issues/40, so I'm closing this issue as a duplicate of that one, but please feel free to discuss further at Microsoft/QuantumLibraries#40.

**Closed by cgranade** 2019-03-08 07:17 UTC

**Comment by ValentinS4t1qbit** [comment] 2019-03-08 07:35
I see ! Andres suggested we raised an issue on the Quantum repo, and I did
not think about checking for duplicates. If it's already on your radar then
it's all what matters :)

Valentin
