### ISSUE TITLE
VSCode not finding libraries

### ISSUE THREAD

**Issue by bentoper** [microsoft/Quantum#362] opened 2020-05-22 00:18 UTC
I've recently tried to install the QDK via the VSCode extension in both my linux (Ubuntu 19) laptop and my Windows 10 Desktop and in both cases VSCode wasn't able to find the Microsoft libraries even after I was able to execute the code by the `dotnet run` command on the terminal. The code was the sample project code described in the [create new project](https://docs.microsoft.com/en-us/quantum/install-guide/standalone) part of the tutorial. I also didn't have .NET SDK so I installed it but it seems to be working fine. In both computers I got 4 problems all the code, all related to not finding the namespaces.

**Expected behavior**

**Screenshots**

**System information**
 - OS: Windows 10 Home and Ubuntu 19.04
 - VSCode Version 1.45.1, dotnet 3.1.300
First image is Windows
![image](https://user-images.githubusercontent.com/40964933/82618068-633d6380-9ba8-11ea-8bda-0d5b5f56532d.png)
Now Ubuntu
![image](https://user-images.githubusercontent.com/40964933/82618141-8bc55d80-9ba8-11ea-8145-e61c19c22012.png)

**Comment by guenp** [comment] 2020-12-21 17:21
@bentopereira Could you please confirm if this is still an issue with the latest version of the VSCode extension?

**Comment by cgranade** [comment] 2021-07-13 17:29
Since we weren't able to reproduce this, going to go on and close the issue, but please feel free to re-open or to open a new issue on the https://github.com/microsoft/qsharp-compiler/ repo if you encounter this again. Thank you!

**Closed by cgranade** 2021-07-13 17:29 UTC
Labels: bug
